const adventure = [
  'Oh, hey, hi pretty lady. My name\'s Rick. So, you out having a little adventure?',
  'What, are you fighting that guy? You got that under control? You know, because, looks like there\'s a lot of stuff on fire...',
  'Hey, a countdown clock! Man, that is trouble. Situation\'s looking pretty ugly. For such a beautiful woman. If you don\'t mind me saying.',
  'I don\'t want to scare you, but, I\'m an Adventure Sphere. Designed for danger. So, why don\'t you go ahead and have yourself a little lady break, and I\'ll just take it from here.',
  'Here, stand behind me. Yeah, just like that. Just like you\'re doing. Things are about to get real messy.',
  'Going for it yourself, huh? All right, angel. I\'ll do what I can to cover you.',
  'Doesn\'t bother me. I gotta say, the view\'s mighty nice from right here.',
  'Man, that clock is moving fast. And you are beautiful. Always time to compliment a pretty lady. All right, back to work. Let\'s do this.',
  'I\'ll tell ya, it\'s times like this I wish I had a waist so I could wear all my black belts. Yeah, I\'m a black belt. In pretty much everything. Karate. Larate. Jiu Jitsu. Kick punching. Belt making. Taekwondo... Bedroom.',
  'I am a coiled spring right now. Tension and power. Just... I\'m a muscle. Like a big arm muscle, punching through a brick wall, and it\'s hitting the wall so hard the arm is catching on fire. Oh yeah.',
  'I probably wouldn\'t have let things get this far, but you go ahead and do things your way.',
  'Tell ya what, why don\'t you put me down and I\'ll make a distraction.',
  'All right. You create a distraction then, and I\'ll distract him from YOUR distraction.',
  'All right, your funeral. Your beautiful-lady-corpse open casket funeral.',
  'Do you have a gun? Because I should really have a gun. What is that thing you\'re holding?',
  'How about a knife, then? You keep the gun, I\'ll use a knife.',
  'No knife? That\'s fine. I know all about pressure points.',
  'So, when you kill that guy, do you have a cool line? You know, prepared? Tell you what: Lemme help you with that while you run around.',
  'Okay, let\'s see. Cool line... He\'s... big. He\'s... just hangin\' there. Okay. Yeah, all right, here we go: \'Hang around.\' That might be too easy.',
  '\'Hang ten?\' That might work if there were ten of him. Do you think there might be nine more of this guy somewhere?',
  'All right, you know what, it\'s gonna be best if you can get him to say something first. It\'s just better if I have a set-up.',
  'Here\'s the plan: Get him to say, \'You two have been a thorn in my side long enough.\' Then tell your pretty ears to stand back, because I am going to zing him into the stone age.',
  'Did you hear that? I think something just exploded. Man, we are in a lot of danger. This is like Christmas. No, it\'s better than Christmas. This should be its own holiday. Explosion Day!',
  'Happy Explosion Day, gorgeous.',
  'Get dirty with this robot! This robot owes you money! This robot owes! You! Money!',
  'Here, let me put on some adventure music.',
  'Dun-dun-dun-dun-dun-dun-DUN! DUN DUN! Dunna-dunna-na-dunna-na-DUN! DUN DUN! nananaDUNDUNDUN dun-dun-dun-dun-dun-dun...',
  'Dun-dun-dun-dun-dun-dun-action and adventure-dunna-dunna-na-dunna-na-playing by our own rules-nanana-hanging by our fingers from a mountain-dun-dun-dun-dun-dun-dun...', 
  'Oh, hello angel. I guess I must have died and gone to heaven. Name\'s Rick. So, you out having yourself a little adventure?',
  'Here\'s the plan: Get him to say, \'You two have been a thorn in my side long enough.\' Then tell your pretty ears to stand back, because I am going to zing him into space.',
  '\'Yeah? Well this thorn... is about to take you down.\' Oh yeah!',
  'Okay, have it your way. What, are you fighting that guy? You got that under control there? Cuz it looks like there\'s a lot of stuff on fire...',
  'Kick him! Or punch him. You\'re the boss, dimples.',
  'Yeah! Nice!',
  'You messed with the wrong woman!',
  'Yeah! How\'d you like that?',
  'How\'s that taste, pal?',
  'Keep it up, baby! You\'re creamin\' him!',
  'Duck and weave, duck and weave! Ohh, the sweet science.',
  'You\'re doing great!',
  'Come on, sweetie! He\'s got a glass jaw! He\'s got a glass everything! This guy\'s a china cabinet!',
  'This ain\'t Marquis of Queensberry Rules, sweetie! Pour on the mustard!',
  'Shake it off! Shake it off!',
  'Pfff. I guess.',
  'Pff. Whatever.',
  'Oh, shut up!',
  'Nobody cares, four eyes.',
  'If you had underwear? And a butt? I would pull your underwear... right up your butt.',
  'Tell it to the bad guy. Maybe you\'ll make him so bored his brain\'ll explode.',
  'You know who found that interesting? Nobody. That didn\'t affect anybody\'s life in any way whatsoever. Life would be exactly the same if you hadn\'t said anything.',
  'You ever notice how nobody stops what they\'re doing to listen? We don\'t care.',
  'Say one useful thing. One. I dare you. I will give you a hundred dollars if you say one thing remotely applicable to anything at all.',
  'Oh shut up!',
  'There\'s nothing in space! That\'s why it\'s space!',
  'Oh, really? Space? Really? You should have said something! We had no idea!',
  'You know what I hope\'s in space? Fire. I hope you go to space and catch on fire.',
  'Dammit, we know! Everybody knows! Space! You! In it! We get it!',
]